import { chromium, firefox } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
import { strict as assert } from 'node:assert';
import { localSite } from './local-site.mjs';
const browserName=process.argv[2]||'chrome';
const label=(process.env.JUNGLE_REPORT_LABEL ? process.env.JUNGLE_REPORT_LABEL+'-' : '')+browserName;
if(!/^[a-z0-9-]+$/.test(label))throw new Error('Invalid smoke report label.');
const browser=browserName==='firefox'?await firefox.launch():await chromium.launch({channel:'chrome'});
const page=await browser.newPage({viewport:{width:1180,height:800}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',response=>{if(response.status()>=400)errors.push(response.status()+' '+response.url());});
page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
mkdirSync('artifacts/screenshots',{recursive:true});
const site=await localSite();
try{
  const start=Date.now();
  await page.goto(site.url);
  await page.locator('[data-engine-ready="true"]').waitFor();
  const startupMs=Date.now()-start;
  assert.equal(await page.locator('[data-square]').count(),63);
  await page.screenshot({path:'artifacts/screenshots/'+label+'-initial.png',fullPage:true});
  await page.getByLabel('Difficulty',{exact:true}).selectOption('easy');
  await page.locator('[data-square="48"]').click();
  assert.equal(await page.locator('[data-square="41"]').getAttribute('data-legal'),'true');
  await page.locator('[data-square="41"]').click();
  await page.waitForFunction(()=>Number(document.querySelector('[data-testid="app"]')?.getAttribute('data-ply'))>=2);
  const responseMs=Number(await page.getByTestId('app').getAttribute('data-response-ms'));
  await page.getByRole('button',{name:'Undo',exact:false}).click();
  assert.equal(await page.getByTestId('app').getAttribute('data-ply'),'0');
  await page.getByRole('button',{name:'Redo',exact:false}).click();
  assert.equal(await page.getByTestId('app').getAttribute('data-ply'),'2');
  await page.getByRole('button',{name:'Flip board',exact:false}).click();
  assert.equal(await page.getByTestId('board').getAttribute('data-flipped'),'true');
  await page.getByRole('button',{name:'How to play',exact:false}).click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('button',{name:'Close dialog'}).click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Save game',exact:true}).click();
  const download=await downloadPromise;await download.saveAs('artifacts/'+label+'-save.json');
  await page.locator('.new-game').click();
  await page.getByRole('button',{name:/Start game/}).click();
  await page.waitForFunction(()=>document.querySelector('[data-testid="app"]')?.getAttribute('data-ply')==='0');
  await page.getByTestId('load-file').setInputFiles('artifacts/'+label+'-save.json');
  await page.waitForFunction(()=>document.querySelector('[data-testid="app"]')?.getAttribute('data-ply')==='2');
  await page.screenshot({path:'artifacts/screenshots/'+label+'-played.png',fullPage:true});
  const report={browser:browserName,version:browser.version(),url:site.url,startupMs,responseMs,errors,passed:errors.length===0};
  writeFileSync('artifacts/'+label+'-smoke.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
  assert.equal(errors.length,0,errors.join('\n'));
}finally{site.close();await browser.close();}
